// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by teleport_router_generator

import 'package:teleport_router/teleport_router.dart';
import 'package:example/guards/auth_guard.dart';
import 'package:example/models/memory_detail.dart';
import 'package:example/pages/dashboard/analytics_page.dart';
import 'package:example/pages/dashboard/dashboard_overview_page.dart';
import 'package:example/pages/dashboard/reports_page.dart';
import 'package:example/pages/details_page.dart';
import 'package:example/pages/login_page.dart';
import 'package:example/pages/main/home_page.dart';
import 'package:example/pages/main/main_shell_page.dart';
import 'package:example/pages/main/settings_page.dart';
import 'package:example/pages/memory_detail_page.dart';
import 'package:example/pages/protected_page.dart';
import 'package:example/pages/route_removal_demo_page.dart';
import 'package:example/pages/user_page.dart';
import 'package:example/routes/nav_keys.dart';

/// Route class for [AnalyticsPage].
///
/// Usage:
/// ```dart
/// AnalyticsRoute().teleport();
/// ```
class AnalyticsRoute extends TeleportRouteData {
  final String? title;

  const AnalyticsRoute({
    this.title,
  });

  @override
  String get routeName => 'teleport_router_AnalyticsRoute';

  static const String kName = 'teleport_router_AnalyticsRoute';

  /// Creates a [AnalyticsRoute] from [TeleportRouteData].
  static AnalyticsRoute fromData(TeleportRouteData data) {
    if (data is AnalyticsRoute) return data;
    final settings = data;
    final title = (() {
      // Try getting from extra/map first via operator []
      final val = settings['title'];
      if (val is String) {
        return val;
      }
      return null;
    })();
    return AnalyticsRoute(title: title);
  }

  /// The route info for this route.
  static final TeleportRouteInfo routeInfo = TeleportRouteInfo(
    path: '/dashboard/analytics',
    name: 'teleport_router_AnalyticsRoute',
    isInitial: false,
    params: [
      TeleportParamInfo(
        name: 'title',
        urlName: 'title',
        type: 'String?',
        isRequired: false,
        source: 'extra',
      ),
    ],
    builder: (settings) {
      final title = (() {
        // Try getting from extra/map first via operator []
        final val = settings['title'];
        if (val is String) {
          return val;
        }
        return null;
      })();
      return AnalyticsPage(title: title);
    },
  );

  @override
  String get fullPath {
    var p = '/dashboard/analytics';
    return p;
  }

  @override
  Map<String, dynamic> get extra => {
        'title': title,
      };
}

/// Route class for [DashboardOverviewPage].
///
/// Usage:
/// ```dart
/// DashboardOverviewRoute().teleport();
/// ```
class DashboardOverviewRoute extends TeleportRouteData {
  const DashboardOverviewRoute();

  @override
  String get routeName => 'teleport_router_DashboardOverviewRoute';

  static const String kName = 'teleport_router_DashboardOverviewRoute';

  /// Creates a [DashboardOverviewRoute] from [TeleportRouteData].
  static DashboardOverviewRoute fromData(TeleportRouteData data) {
    if (data is DashboardOverviewRoute) return data;
    final settings = data;
    return DashboardOverviewRoute();
  }

  /// The route info for this route.
  static final TeleportRouteInfo routeInfo = TeleportRouteInfo(
    path: '/dashboard/overview',
    name: 'teleport_router_DashboardOverviewRoute',
    isInitial: false,
    params: [],
    builder: (settings) {
      return DashboardOverviewPage();
    },
  );

  @override
  String get fullPath {
    var p = '/dashboard/overview';
    return p;
  }
}

/// Route class for [ReportsPage].
///
/// Usage:
/// ```dart
/// ReportsRoute().teleport();
/// ```
class ReportsRoute extends TeleportRouteData {
  const ReportsRoute();

  @override
  String get routeName => 'teleport_router_ReportsRoute';

  static const String kName = 'teleport_router_ReportsRoute';

  /// Creates a [ReportsRoute] from [TeleportRouteData].
  static ReportsRoute fromData(TeleportRouteData data) {
    if (data is ReportsRoute) return data;
    final settings = data;
    return ReportsRoute();
  }

  /// The route info for this route.
  static final TeleportRouteInfo routeInfo = TeleportRouteInfo(
    path: '/dashboard/reports',
    name: 'teleport_router_ReportsRoute',
    isInitial: false,
    params: [],
    builder: (settings) {
      return ReportsPage();
    },
  );

  @override
  String get fullPath {
    var p = '/dashboard/reports';
    return p;
  }
}

/// Route class for [DetailsPage].
///
/// Usage:
/// ```dart
/// DetailsRoute().teleport();
/// ```
class DetailsRoute extends TeleportRouteData {
  final String title;
  final int level;

  const DetailsRoute({
    this.title = 'Details',
    this.level = 1,
  });

  @override
  String get routeName => 'teleport_router_DetailsRoute';

  static const String kName = 'teleport_router_DetailsRoute';

  /// Creates a [DetailsRoute] from [TeleportRouteData].
  static DetailsRoute fromData(TeleportRouteData data) {
    if (data is DetailsRoute) return data;
    final settings = data;
    final title = (() {
      // Try getting from extra/map first via operator []
      final val = settings['title'];
      if (val is String) {
        return val;
      }
      return null;
    })();
    final level = (() {
      final raw = settings.queryParams['level'];
      if (raw == null) {
        return null;
      }
      final parsed = int.tryParse(raw);
      if (parsed == null) {
        return null;
      }
      return parsed;
    })();
    return DetailsRoute(title: (title ?? 'Details'), level: (level ?? 1));
  }

  /// The route info for this route.
  static final TeleportRouteInfo routeInfo = TeleportRouteInfo(
    path: '/details',
    name: 'teleport_router_DetailsRoute',
    isInitial: false,
    params: [
      TeleportParamInfo(
        name: 'title',
        urlName: 'title',
        type: 'String',
        isRequired: false,
        source: 'extra',
      ),
      TeleportParamInfo(
        name: 'level',
        urlName: 'level',
        type: 'int',
        isRequired: false,
        source: 'query',
      ),
    ],
    builder: (settings) {
      final title = (() {
        // Try getting from extra/map first via operator []
        final val = settings['title'];
        if (val is String) {
          return val;
        }
        return null;
      })();
      final level = (() {
        final raw = settings.queryParams['level'];
        if (raw == null) {
          return null;
        }
        final parsed = int.tryParse(raw);
        if (parsed == null) {
          return null;
        }
        return parsed;
      })();
      return DetailsPage(title: (title ?? 'Details'), level: (level ?? 1));
    },
    transition: const TeleportSlideTransition(),
    transitionDuration: const Duration(microseconds: 500000),
    reverseTransitionDuration: const Duration(microseconds: 300000),
  );

  @override
  String get fullPath {
    var p = '/details';
    final queryParts = <String>[];
    queryParts.add('level=${Uri.encodeComponent(level.toString())}');
    if (queryParts.isNotEmpty) p = '$p?${queryParts.join('&')}';
    return p;
  }

  @override
  Map<String, dynamic> get extra => {
        'title': title,
      };
}

/// Route class for [LoginPage].
///
/// Usage:
/// ```dart
/// LoginRoute().teleport();
/// ```
class LoginRoute extends TeleportRouteData {
  const LoginRoute();

  @override
  String get routeName => 'teleport_router_LoginRoute';

  static const String kName = 'teleport_router_LoginRoute';

  /// Creates a [LoginRoute] from [TeleportRouteData].
  static LoginRoute fromData(TeleportRouteData data) {
    if (data is LoginRoute) return data;
    final settings = data;
    return LoginRoute();
  }

  /// The route info for this route.
  static final TeleportRouteInfo routeInfo = TeleportRouteInfo(
    path: '/login',
    name: 'teleport_router_LoginRoute',
    isInitial: false,
    params: [],
    builder: (settings) {
      return LoginPage();
    },
  );

  @override
  String get fullPath {
    var p = '/login';
    return p;
  }
}

/// Route class for [HomePage].
///
/// Usage:
/// ```dart
/// HomeRoute().teleport();
/// ```
class HomeRoute extends TeleportRouteData {
  const HomeRoute();

  @override
  String get routeName => 'teleport_router_HomeRoute';

  static const String kName = 'teleport_router_HomeRoute';

  /// Creates a [HomeRoute] from [TeleportRouteData].
  static HomeRoute fromData(TeleportRouteData data) {
    if (data is HomeRoute) return data;
    final settings = data;
    return HomeRoute();
  }

  /// The route info for this route.
  static final TeleportRouteInfo routeInfo = TeleportRouteInfo(
    path: '/',
    name: 'teleport_router_HomeRoute',
    isInitial: true,
    params: [],
    builder: (settings) {
      return HomePage();
    },
  );

  @override
  String get fullPath {
    var p = '/';
    return p;
  }
}

class MainShellRoute {
  static final navigatorKey = MainNavKey();

  static final TeleportStatefulShellRouteInfo routeInfo =
      TeleportStatefulShellRouteInfo(
    builder: (context, navigationShell) =>
        MainShellPage(navigationShell: navigationShell),
    branches: [
      [
        DetailsRoute.routeInfo,
        LoginRoute.routeInfo,
        HomeRoute.routeInfo,
        ProtectedRoute.routeInfo,
        UserRoute.routeInfo,
      ],
      [
        SettingsRoute.routeInfo,
      ],
      [
        AnalyticsRoute.routeInfo,
        DashboardOverviewRoute.routeInfo,
        ReportsRoute.routeInfo,
      ],
    ],
    branchNavigatorKeys: [
      MainHomeNavKey(),
      MainSettingNavKey(),
      MainDashBoradNavKey(),
    ],
    observersBuilder: () => [
      AObserver(),
    ],
  );
}

/// Route class for [SettingsPage].
///
/// Usage:
/// ```dart
/// SettingsRoute().teleport();
/// ```
class SettingsRoute extends TeleportRouteData {
  const SettingsRoute();

  @override
  String get routeName => 'teleport_router_SettingsRoute';

  static const String kName = 'teleport_router_SettingsRoute';

  /// Creates a [SettingsRoute] from [TeleportRouteData].
  static SettingsRoute fromData(TeleportRouteData data) {
    if (data is SettingsRoute) return data;
    final settings = data;
    return SettingsRoute();
  }

  /// The route info for this route.
  static final TeleportRouteInfo routeInfo = TeleportRouteInfo(
    path: '/settings',
    name: 'teleport_router_SettingsRoute',
    isInitial: false,
    params: [],
    builder: (settings) {
      return SettingsPage();
    },
  );

  @override
  String get fullPath {
    var p = '/settings';
    return p;
  }
}

/// Route class for [MemoryDetailPage].
///
/// Usage:
/// ```dart
/// MemoryDetailRoute(memory2: value).teleport();
/// ```
class MemoryDetailRoute extends TeleportRouteData {
  final MemoryDetail memory2;
  final MemoryDetail memory;

  const MemoryDetailRoute({
    required this.memory2,
    this.memory =
        const MemoryDetail(id: 'internal', content: 'Internal Default'),
  });

  @override
  String get routeName => 'teleport_router_MemoryDetailRoute';

  static const String kName = 'teleport_router_MemoryDetailRoute';

  /// Creates a [MemoryDetailRoute] from [TeleportRouteData].
  static MemoryDetailRoute fromData(TeleportRouteData data) {
    if (data is MemoryDetailRoute) return data;
    final settings = data;
    final memory2 = (() {
      // Try getting from map first
      final val = settings['memory2'];
      if (val is MemoryDetail) return val;

      // Try casting the whole extra object
      final asType = settings.getExtraAs<MemoryDetail>();
      if (asType != null) return asType;

      throw ArgumentError('Missing required parameter: memory2');
    })();
    final memory = (() {
      // Try getting from map first
      final val = settings['memory'];
      if (val is MemoryDetail) return val;

      // Try casting the whole extra object
      final asType = settings.getExtraAs<MemoryDetail>();
      if (asType != null) return asType;

      return null;
    })();
    return MemoryDetailRoute(
        memory2: memory2,
        memory: (memory ??
            const MemoryDetail(id: 'internal', content: 'Internal Default')));
  }

  /// The route info for this route.
  static final TeleportRouteInfo routeInfo = TeleportRouteInfo(
    path: '/memory-detail',
    name: 'teleport_router_MemoryDetailRoute',
    isInitial: false,
    params: [
      TeleportParamInfo(
        name: 'memory2',
        urlName: 'memory2',
        type: 'MemoryDetail',
        isRequired: true,
        source: 'extra',
      ),
      TeleportParamInfo(
        name: 'memory',
        urlName: 'memory',
        type: 'MemoryDetail',
        isRequired: false,
        source: 'extra',
      ),
    ],
    builder: (settings) {
      final memory2 = (() {
        // Try getting from map first
        final val = settings['memory2'];
        if (val is MemoryDetail) return val;

        // Try casting the whole extra object
        final asType = settings.getExtraAs<MemoryDetail>();
        if (asType != null) return asType;

        throw ArgumentError('Missing required parameter: memory2');
      })();
      final memory = (() {
        // Try getting from map first
        final val = settings['memory'];
        if (val is MemoryDetail) return val;

        // Try casting the whole extra object
        final asType = settings.getExtraAs<MemoryDetail>();
        if (asType != null) return asType;

        return null;
      })();
      return MemoryDetailPage(
          memory2: memory2,
          memory: (memory ??
              const MemoryDetail(id: 'internal', content: 'Internal Default')));
    },
  );

  @override
  String get fullPath {
    var p = '/memory-detail';
    return p;
  }

  @override
  Map<String, dynamic> get extra => {
        'memory2': memory2,
        'memory': memory,
      };
}

/// Route class for [ProtectedPage].
///
/// Usage:
/// ```dart
/// ProtectedRoute().teleport();
/// ```
class ProtectedRoute extends TeleportRouteData {
  const ProtectedRoute();

  @override
  String get routeName => 'teleport_router_ProtectedRoute';

  static const String kName = 'teleport_router_ProtectedRoute';

  /// Creates a [ProtectedRoute] from [TeleportRouteData].
  static ProtectedRoute fromData(TeleportRouteData data) {
    if (data is ProtectedRoute) return data;
    final settings = data;
    return ProtectedRoute();
  }

  /// The route info for this route.
  static final TeleportRouteInfo routeInfo = TeleportRouteInfo(
    path: '/protected',
    name: 'teleport_router_ProtectedRoute',
    isInitial: false,
    params: [],
    redirect: (context, data) async {
      final route = ProtectedRoute.fromData(data);
      return AuthRedirect().handle(context, route);
    },
    builder: (settings) {
      return ProtectedPage();
    },
  );

  @override
  String get fullPath {
    var p = '/protected';
    return p;
  }
}

/// Route class for [RouteRemovalDemoPage].
///
/// Usage:
/// ```dart
/// RouteRemovalDemoRoute().teleport();
/// ```
class RouteRemovalDemoRoute extends TeleportRouteData {
  const RouteRemovalDemoRoute();

  @override
  String get routeName => 'teleport_router_RouteRemovalDemoRoute';

  static const String kName = 'teleport_router_RouteRemovalDemoRoute';

  /// Creates a [RouteRemovalDemoRoute] from [TeleportRouteData].
  static RouteRemovalDemoRoute fromData(TeleportRouteData data) {
    if (data is RouteRemovalDemoRoute) return data;
    final settings = data;
    return RouteRemovalDemoRoute();
  }

  /// The route info for this route.
  static final TeleportRouteInfo routeInfo = TeleportRouteInfo(
    path: '/route-removal-demo',
    name: 'teleport_router_RouteRemovalDemoRoute',
    isInitial: false,
    params: [],
    builder: (settings) {
      return RouteRemovalDemoPage();
    },
  );

  @override
  String get fullPath {
    var p = '/route-removal-demo';
    return p;
  }
}

/// Route class for [RouteStackPageA].
///
/// Usage:
/// ```dart
/// RouteStackPageARoute().teleport();
/// ```
class RouteStackPageARoute extends TeleportRouteData {
  const RouteStackPageARoute();

  @override
  String get routeName => 'teleport_router_RouteStackPageARoute';

  static const String kName = 'teleport_router_RouteStackPageARoute';

  /// Creates a [RouteStackPageARoute] from [TeleportRouteData].
  static RouteStackPageARoute fromData(TeleportRouteData data) {
    if (data is RouteStackPageARoute) return data;
    final settings = data;
    return RouteStackPageARoute();
  }

  /// The route info for this route.
  static final TeleportRouteInfo routeInfo = TeleportRouteInfo(
    path: '/route-stack/a',
    name: 'teleport_router_RouteStackPageARoute',
    isInitial: false,
    params: [],
    builder: (settings) {
      return RouteStackPageA();
    },
  );

  @override
  String get fullPath {
    var p = '/route-stack/a';
    return p;
  }
}

/// Route class for [RouteStackPageB].
///
/// Usage:
/// ```dart
/// RouteStackPageBRoute().teleport();
/// ```
class RouteStackPageBRoute extends TeleportRouteData {
  const RouteStackPageBRoute();

  @override
  String get routeName => 'teleport_router_RouteStackPageBRoute';

  static const String kName = 'teleport_router_RouteStackPageBRoute';

  /// Creates a [RouteStackPageBRoute] from [TeleportRouteData].
  static RouteStackPageBRoute fromData(TeleportRouteData data) {
    if (data is RouteStackPageBRoute) return data;
    final settings = data;
    return RouteStackPageBRoute();
  }

  /// The route info for this route.
  static final TeleportRouteInfo routeInfo = TeleportRouteInfo(
    path: '/route-stack/b',
    name: 'teleport_router_RouteStackPageBRoute',
    isInitial: false,
    params: [],
    builder: (settings) {
      return RouteStackPageB();
    },
  );

  @override
  String get fullPath {
    var p = '/route-stack/b';
    return p;
  }
}

/// Route class for [RouteStackPageC].
///
/// Usage:
/// ```dart
/// RouteStackPageCRoute().teleport();
/// ```
class RouteStackPageCRoute extends TeleportRouteData {
  const RouteStackPageCRoute();

  @override
  String get routeName => 'teleport_router_RouteStackPageCRoute';

  static const String kName = 'teleport_router_RouteStackPageCRoute';

  /// Creates a [RouteStackPageCRoute] from [TeleportRouteData].
  static RouteStackPageCRoute fromData(TeleportRouteData data) {
    if (data is RouteStackPageCRoute) return data;
    final settings = data;
    return RouteStackPageCRoute();
  }

  /// The route info for this route.
  static final TeleportRouteInfo routeInfo = TeleportRouteInfo(
    path: '/route-stack/c',
    name: 'teleport_router_RouteStackPageCRoute',
    isInitial: false,
    params: [],
    builder: (settings) {
      return RouteStackPageC();
    },
  );

  @override
  String get fullPath {
    var p = '/route-stack/c';
    return p;
  }
}

/// Route class for [UserPage].
///
/// Usage:
/// ```dart
/// UserRoute(id: 123).teleport();
/// ```
class UserRoute extends TeleportRouteData {
  final int id;
  final String name;
  final int age;

  const UserRoute({
    required this.id,
    this.name = '',
    this.age = 0,
  });

  @override
  String get routeName => 'teleport_router_UserRoute';

  static const String kName = 'teleport_router_UserRoute';

  /// Creates a [UserRoute] from [TeleportRouteData].
  static UserRoute fromData(TeleportRouteData data) {
    if (data is UserRoute) return data;
    final settings = data;
    final id = (() {
      final raw = settings.pathParams['id'];
      if (raw == null) {
        throw ArgumentError('Missing required parameter: id');
      }
      final parsed = int.tryParse(raw);
      if (parsed == null) {
        throw ArgumentError('Invalid int value for: id');
      }
      return parsed;
    })();
    final name = settings.queryParams['name'];
    final age = (() {
      final raw = settings.queryParams['age'];
      if (raw == null) {
        return null;
      }
      final parsed = int.tryParse(raw);
      if (parsed == null) {
        return null;
      }
      return parsed;
    })();
    return UserRoute(id: id, name: (name ?? ''), age: (age ?? 0));
  }

  /// The route info for this route.
  static final TeleportRouteInfo routeInfo = TeleportRouteInfo(
    path: '/user/:id',
    name: 'teleport_router_UserRoute',
    isInitial: false,
    params: [
      TeleportParamInfo(
        name: 'id',
        urlName: 'id',
        type: 'int',
        isRequired: true,
        source: 'path',
      ),
      TeleportParamInfo(
        name: 'name',
        urlName: 'name',
        type: 'String',
        isRequired: false,
        source: 'query',
      ),
      TeleportParamInfo(
        name: 'age',
        urlName: 'age',
        type: 'int',
        isRequired: false,
        source: 'query',
      ),
    ],
    builder: (settings) {
      final id = (() {
        final raw = settings.pathParams['id'];
        if (raw == null) {
          throw ArgumentError('Missing required parameter: id');
        }
        final parsed = int.tryParse(raw);
        if (parsed == null) {
          throw ArgumentError('Invalid int value for: id');
        }
        return parsed;
      })();
      final name = settings.queryParams['name'];
      final age = (() {
        final raw = settings.queryParams['age'];
        if (raw == null) {
          return null;
        }
        final parsed = int.tryParse(raw);
        if (parsed == null) {
          return null;
        }
        return parsed;
      })();
      return UserPage(id: id, name: (name ?? ''), age: (age ?? 0));
    },
  );

  @override
  String get fullPath {
    var p = '/user/:id';
    p = p.replaceAll(':id', id.toString());
    final queryParts = <String>[];
    queryParts.add('name=${Uri.encodeComponent(name.toString())}');
    queryParts.add('age=${Uri.encodeComponent(age.toString())}');
    if (queryParts.isNotEmpty) p = '$p?${queryParts.join('&')}';
    return p;
  }
}

/// All generated routes in the application.
///
/// Use this list to initialize [TeleportRouter]:
/// ```dart
/// final router = TeleportRouter(routes: teleportRoutes);
/// ```
List<TeleportRouteBase> get teleportRoutes => [
      MainShellRoute.routeInfo,
      MemoryDetailRoute.routeInfo,
      RouteRemovalDemoRoute.routeInfo,
      RouteStackPageARoute.routeInfo,
      RouteStackPageBRoute.routeInfo,
      RouteStackPageCRoute.routeInfo,
    ];
