// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by tp_router_generator

import 'package:tp_router/tp_router.dart';
import 'package:example/guards/auth_guard.dart';
import 'package:example/pages/dashboard/analytics_page.dart';
import 'package:example/pages/dashboard/dashboard_overview_page.dart';
import 'package:example/pages/dashboard/dashboard_shell.dart';
import 'package:example/pages/dashboard/reports_page.dart';
import 'package:example/pages/details_page.dart';
import 'package:example/pages/home_page.dart';
import 'package:example/pages/login_page.dart';
import 'package:example/pages/main_shell_page.dart';
import 'package:example/pages/protected_page.dart';
import 'package:example/pages/settings_page.dart';
import 'package:example/pages/user_page.dart';

/// Route class for [AnalyticsPage].
///
/// Usage:
/// ```dart
/// AnalyticsRoute().tp(context);
/// ```
class AnalyticsRoute extends TpRouteData {
  const AnalyticsRoute();

  /// The route path.
  static const String path = '/dashboard/analytics';

  /// The route info for this route.
  static final TpRouteInfo routeInfo = TpRouteInfo(
    path: '/dashboard/analytics',
    isInitial: false,
    params: [
    ],
    builder: (_) {
      return AnalyticsPage();
    },
  );

  @override
  String get fullPath {
    var p = '/dashboard/analytics';
    return p;
  }

}


/// Route class for [DashboardOverviewPage].
///
/// Usage:
/// ```dart
/// DashboardOverviewRoute().tp(context);
/// ```
class DashboardOverviewRoute extends TpRouteData {
  const DashboardOverviewRoute();

  /// The route path.
  static const String path = '/dashboard/overview';

  /// The route info for this route.
  static final TpRouteInfo routeInfo = TpRouteInfo(
    path: '/dashboard/overview',
    isInitial: false,
    params: [
    ],
    builder: (_) {
      return DashboardOverviewPage();
    },
  );

  @override
  String get fullPath {
    var p = '/dashboard/overview';
    return p;
  }

}


class DashboardShellRoute {
  static final TpShellRouteInfo routeInfo = TpShellRouteInfo(
    builder: (context, child) => DashboardShell(child: child),
    routes: [
      DashboardOverviewRoute.routeInfo,
      AnalyticsRoute.routeInfo,
      ReportsRoute.routeInfo,
    ],
  );
}


/// Route class for [ReportsPage].
///
/// Usage:
/// ```dart
/// ReportsRoute().tp(context);
/// ```
class ReportsRoute extends TpRouteData {
  const ReportsRoute();

  /// The route path.
  static const String path = '/dashboard/reports';

  /// The route info for this route.
  static final TpRouteInfo routeInfo = TpRouteInfo(
    path: '/dashboard/reports',
    isInitial: false,
    params: [
    ],
    builder: (_) {
      return ReportsPage();
    },
  );

  @override
  String get fullPath {
    var p = '/dashboard/reports';
    return p;
  }

}


/// Route class for [DetailsPage].
///
/// Usage:
/// ```dart
/// DetailsRoute().tp(context);
/// ```
class DetailsRoute extends TpRouteData {
  final String title;
  final int level;

  const DetailsRoute({
    this.title = 'Details',
    this.level = 1,
  });

  /// The route path.
  static const String path = '/details';

  /// The route info for this route.
  static final TpRouteInfo routeInfo = TpRouteInfo(
    path: '/details',
    isInitial: false,
    params: [
      TpParamInfo(
        name: 'title',
        urlName: 'title',
        type: 'String',
        isRequired: false,
        source: 'extra',
      ),
      TpParamInfo(
        name: 'level',
        urlName: 'level',
        type: 'int',
        isRequired: false,
        source: 'query',
      ),
    ],
    builder: (settings) {
    final title = (() {
      final extraValue = settings.extra['title'];
      if (extraValue is String) {
        return extraValue;
      }
      return settings.pathParams['title'] ?? settings.queryParams['title'] ?? null;
    })();
    final level = (() {

      final raw = settings.queryParams['level'];
      if (raw == null) {
        return null;
      }
      final parsed = int.tryParse(raw);
      if (parsed == null) {
        return null;
      }
      return parsed;
    })();
      return DetailsPage(title: title ?? 'Details', level: level ?? 1);
    },
    transition: const TpSlideTransition(),
    transitionDuration: const Duration(microseconds: 500000),
    reverseTransitionDuration: const Duration(microseconds: 300000),
  );

  @override
  String get fullPath {
    var p = '/details';
    final queryParts = <String>[];
    queryParts.add('level=${Uri.encodeComponent(level.toString())}');
    if (queryParts.isNotEmpty) p = '$p?${queryParts.join('&')}';
    return p;
  }

  @override
  Map<String, dynamic> get extra => {
    'title': title,
  };

}


/// Route class for [HomePage].
///
/// Usage:
/// ```dart
/// HomeRoute().tp(context);
/// ```
class HomeRoute extends TpRouteData {
  const HomeRoute();

  /// The route path.
  static const String path = '/';

  /// The route info for this route.
  static final TpRouteInfo routeInfo = TpRouteInfo(
    path: '/',
    isInitial: true,
    params: [
    ],
    builder: (_) {
      return HomePage();
    },
  );

  @override
  String get fullPath {
    var p = '/';
    return p;
  }

}


/// Route class for [LoginPage].
///
/// Usage:
/// ```dart
/// LoginRoute().tp(context);
/// ```
class LoginRoute extends TpRouteData {
  const LoginRoute();

  /// The route path.
  static const String path = '/login';

  /// The route info for this route.
  static final TpRouteInfo routeInfo = TpRouteInfo(
    path: '/login',
    isInitial: false,
    params: [
    ],
    builder: (_) {
      return LoginPage();
    },
  );

  @override
  String get fullPath {
    var p = '/login';
    return p;
  }

}


class MainShellRoute {
  static final TpStatefulShellRouteInfo routeInfo = TpStatefulShellRouteInfo(
    builder: (context, navigationShell) => MainShellPage(navigationShell: navigationShell),
    branches: [
      [
        HomeRoute.routeInfo,
      ],
      [
        SettingsRoute.routeInfo,
      ],
      [
        DashboardShellRoute.routeInfo,
      ],
    ],
  );
}


/// Route class for [ProtectedPage].
///
/// Usage:
/// ```dart
/// ProtectedRoute().tp(context);
/// ```
class ProtectedRoute extends TpRouteData {
  const ProtectedRoute();

  /// The route path.
  static const String path = '/protected';

  /// The route info for this route.
  static final TpRouteInfo routeInfo = TpRouteInfo(
    path: '/protected',
    isInitial: false,
    params: [
    ],
    redirect: (context, _) async {
      final route = ProtectedRoute();
      return authRedirect(context, route);
    },
    builder: (_) {
      return ProtectedPage();
    },
  );

  @override
  String get fullPath {
    var p = '/protected';
    return p;
  }

}


/// Route class for [SettingsPage].
///
/// Usage:
/// ```dart
/// SettingsRoute().tp(context);
/// ```
class SettingsRoute extends TpRouteData {
  const SettingsRoute();

  /// The route path.
  static const String path = '/settings';

  /// The route info for this route.
  static final TpRouteInfo routeInfo = TpRouteInfo(
    path: '/settings',
    name: 'settings',
    isInitial: false,
    params: [
    ],
    builder: (_) {
      return SettingsPage();
    },
  );

  @override
  String get fullPath {
    var p = '/settings';
    return p;
  }

}


/// Route class for [UserPage].
///
/// Usage:
/// ```dart
/// UserRoute(id: 123).tp(context);
/// ```
class UserRoute extends TpRouteData {
  final int id;
  final String name;
  final int age;

  const UserRoute({
    required this.id,
    this.name = '',
    this.age = 0,
  });

  /// The route path.
  static const String path = '/user/:id';

  /// The route info for this route.
  static final TpRouteInfo routeInfo = TpRouteInfo(
    path: '/user/:id',
    name: 'user',
    isInitial: false,
    params: [
      TpParamInfo(
        name: 'id',
        urlName: 'id',
        type: 'int',
        isRequired: true,
        source: 'path',
      ),
      TpParamInfo(
        name: 'name',
        urlName: 'name',
        type: 'String',
        isRequired: false,
        source: 'query',
      ),
      TpParamInfo(
        name: 'age',
        urlName: 'age',
        type: 'int',
        isRequired: false,
        source: 'query',
      ),
    ],
    builder: (settings) {
    final id = (() {

      final raw = settings.pathParams['id'];
      if (raw == null) {
        throw ArgumentError('Missing required parameter: id');
      }
      final parsed = int.tryParse(raw);
      if (parsed == null) {
        throw ArgumentError('Invalid int value for: id');
      }
      return parsed;
    })();
    final name = settings.queryParams['name'];
    final age = (() {

      final raw = settings.queryParams['age'];
      if (raw == null) {
        return null;
      }
      final parsed = int.tryParse(raw);
      if (parsed == null) {
        return null;
      }
      return parsed;
    })();
      return UserPage(id: id, name: name ?? '', age: age ?? 0);
    },
  );

  @override
  String get fullPath {
    var p = '/user/:id';
    p = p.replaceAll(':id', id.toString());
    final queryParts = <String>[];
    queryParts.add('name=${Uri.encodeComponent(name.toString())}');
    queryParts.add('age=${Uri.encodeComponent(age.toString())}');
    if (queryParts.isNotEmpty) p = '$p?${queryParts.join('&')}';
    return p;
  }

}


/// All generated routes in the application.
///
/// Use this list to initialize [TpRouter]:
/// ```dart
/// final router = TpRouter(routes: tpRoutes);
/// ```
List<TpRouteBase> get tpRoutes => [
  DetailsRoute.routeInfo,
  LoginRoute.routeInfo,
  MainShellRoute.routeInfo,
  ProtectedRoute.routeInfo,
  UserRoute.routeInfo,
];
