// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by tp_router_generator

import 'package:tp_router/tp_router.dart';
import 'package:example/guards/auth_guard.dart';
import 'package:example/models/memory_detail.dart';
import 'package:example/pages/dashboard/analytics_page.dart';
import 'package:example/pages/dashboard/dashboard_overview_page.dart';
import 'package:example/pages/dashboard/dashboard_shell.dart';
import 'package:example/pages/dashboard/reports_page.dart';
import 'package:example/pages/details_page.dart';
import 'package:example/pages/login_page.dart';
import 'package:example/pages/main/home_page.dart';
import 'package:example/pages/main/main_shell_page.dart';
import 'package:example/pages/main/settings_page.dart';
import 'package:example/pages/memory_detail_page.dart';
import 'package:example/pages/protected_page.dart';
import 'package:example/pages/route_removal_demo_page.dart';
import 'package:example/pages/user_page.dart';
import 'package:example/routes/nav_keys.dart';

/// Route class for [AnalyticsPage].
///
/// Usage:
/// ```dart
/// AnalyticsRoute().tp(context);
/// ```
class AnalyticsRoute extends TpRouteData {
  final String? title;

  const AnalyticsRoute({
    this.title,
  });

  @override
  String get routeName => 'tp_router_AnalyticsRoute';

  static const String kName = 'tp_router_AnalyticsRoute';

  /// Creates a [AnalyticsRoute] from [TpRouteData].
  static AnalyticsRoute fromData(TpRouteData data) {
    if (data is AnalyticsRoute) return data;
    final settings = data;
    final title = (() {
      final extraValue = settings.extra?['title'];
      if (extraValue is String) {
        return extraValue;
      }
      return settings.pathParams['title'] ?? settings.queryParams['title'];
    })();
    return AnalyticsRoute(title: title);
  }

  /// The route info for this route.
  static final TpRouteInfo routeInfo = TpRouteInfo(
    path: '/dashboard/analytics',
    name: 'tp_router_AnalyticsRoute',
    isInitial: false,
    params: [
      TpParamInfo(
        name: 'title',
        urlName: 'title',
        type: 'String?',
        isRequired: false,
        source: 'extra',
      ),
    ],
    builder: (settings) {
      final title = (() {
        final extraValue = settings.extra?['title'];
        if (extraValue is String) {
          return extraValue;
        }
        return settings.pathParams['title'] ?? settings.queryParams['title'];
      })();
      return AnalyticsPage(title: title);
    },
  );

  @override
  String get fullPath {
    var p = '/dashboard/analytics';
    return p;
  }

  @override
  Map<String, dynamic> get extra => {
        'title': title,
      };
}

/// Route class for [DashboardOverviewPage].
///
/// Usage:
/// ```dart
/// DashboardOverviewRoute().tp(context);
/// ```
class DashboardOverviewRoute extends TpRouteData {
  const DashboardOverviewRoute();

  @override
  String get routeName => 'tp_router_DashboardOverviewRoute';

  static const String kName = 'tp_router_DashboardOverviewRoute';

  /// Creates a [DashboardOverviewRoute] from [TpRouteData].
  static DashboardOverviewRoute fromData(TpRouteData data) {
    if (data is DashboardOverviewRoute) return data;
    final settings = data;
    return DashboardOverviewRoute();
  }

  /// The route info for this route.
  static final TpRouteInfo routeInfo = TpRouteInfo(
    path: '/dashboard/overview',
    name: 'tp_router_DashboardOverviewRoute',
    isInitial: true,
    params: [],
    builder: (settings) {
      return DashboardOverviewPage();
    },
  );

  @override
  String get fullPath {
    var p = '/dashboard/overview';
    return p;
  }
}

class DashboardShellRoute {
  static final navigatorGlobalKey = const DashboardNavKey().globalKey;
  static const navigatorKey = DashboardNavKey();

  static final TpShellRouteInfo routeInfo = TpShellRouteInfo(
    builder: (context, child) => DashboardShell(child: child),
    navigatorKey: navigatorGlobalKey,
    routes: [
      AnalyticsRoute.routeInfo,
      DashboardOverviewRoute.routeInfo,
      ReportsRoute.routeInfo,
    ],
    observers: [
      DashboardObserver(),
    ],
  );
}

/// Route class for [ReportsPage].
///
/// Usage:
/// ```dart
/// ReportsRoute().tp(context);
/// ```
class ReportsRoute extends TpRouteData {
  const ReportsRoute();

  @override
  String get routeName => 'tp_router_ReportsRoute';

  static const String kName = 'tp_router_ReportsRoute';

  /// Creates a [ReportsRoute] from [TpRouteData].
  static ReportsRoute fromData(TpRouteData data) {
    if (data is ReportsRoute) return data;
    final settings = data;
    return ReportsRoute();
  }

  /// The route info for this route.
  static final TpRouteInfo routeInfo = TpRouteInfo(
    path: '/dashboard/reports',
    name: 'tp_router_ReportsRoute',
    isInitial: false,
    params: [],
    builder: (settings) {
      return ReportsPage();
    },
  );

  @override
  String get fullPath {
    var p = '/dashboard/reports';
    return p;
  }
}

/// Route class for [DetailsPage].
///
/// Usage:
/// ```dart
/// DetailsRoute().tp(context);
/// ```
class DetailsRoute extends TpRouteData {
  final String title;
  final int level;

  const DetailsRoute({
    this.title = 'Details',
    this.level = 1,
  });

  @override
  String get routeName => 'tp_router_DetailsRoute';

  static const String kName = 'tp_router_DetailsRoute';

  /// Creates a [DetailsRoute] from [TpRouteData].
  static DetailsRoute fromData(TpRouteData data) {
    if (data is DetailsRoute) return data;
    final settings = data;
    final title = (() {
      final extraValue = settings.extra?['title'];
      if (extraValue is String) {
        return extraValue;
      }
      return settings.pathParams['title'] ?? settings.queryParams['title'];
    })();
    final level = (() {
      final raw = settings.queryParams['level'];
      if (raw == null) {
        return null;
      }
      final parsed = int.tryParse(raw);
      if (parsed == null) {
        return null;
      }
      return parsed;
    })();
    return DetailsRoute(title: (title ?? 'Details'), level: (level ?? 1));
  }

  /// The route info for this route.
  static final TpRouteInfo routeInfo = TpRouteInfo(
    path: '/details',
    name: 'tp_router_DetailsRoute',
    isInitial: false,
    params: [
      TpParamInfo(
        name: 'title',
        urlName: 'title',
        type: 'String',
        isRequired: false,
        source: 'extra',
      ),
      TpParamInfo(
        name: 'level',
        urlName: 'level',
        type: 'int',
        isRequired: false,
        source: 'query',
      ),
    ],
    builder: (settings) {
      final title = (() {
        final extraValue = settings.extra?['title'];
        if (extraValue is String) {
          return extraValue;
        }
        return settings.pathParams['title'] ?? settings.queryParams['title'];
      })();
      final level = (() {
        final raw = settings.queryParams['level'];
        if (raw == null) {
          return null;
        }
        final parsed = int.tryParse(raw);
        if (parsed == null) {
          return null;
        }
        return parsed;
      })();
      return DetailsPage(title: (title ?? 'Details'), level: (level ?? 1));
    },
    transition: const TpSlideTransition(),
    transitionDuration: const Duration(microseconds: 500000),
    reverseTransitionDuration: const Duration(microseconds: 300000),
  );

  @override
  String get fullPath {
    var p = '/details';
    final queryParts = <String>[];
    queryParts.add('level=${Uri.encodeComponent(level.toString())}');
    if (queryParts.isNotEmpty) p = '$p?${queryParts.join('&')}';
    return p;
  }

  @override
  Map<String, dynamic> get extra => {
        'title': title,
      };
}

/// Route class for [LoginPage].
///
/// Usage:
/// ```dart
/// LoginRoute().tp(context);
/// ```
class LoginRoute extends TpRouteData {
  const LoginRoute();

  @override
  String get routeName => 'tp_router_LoginRoute';

  static const String kName = 'tp_router_LoginRoute';

  /// Creates a [LoginRoute] from [TpRouteData].
  static LoginRoute fromData(TpRouteData data) {
    if (data is LoginRoute) return data;
    final settings = data;
    return LoginRoute();
  }

  /// The route info for this route.
  static final TpRouteInfo routeInfo = TpRouteInfo(
    path: '/login',
    name: 'tp_router_LoginRoute',
    isInitial: false,
    params: [],
    builder: (settings) {
      return LoginPage();
    },
  );

  @override
  String get fullPath {
    var p = '/login';
    return p;
  }
}

/// Route class for [HomePage].
///
/// Usage:
/// ```dart
/// HomeRoute().tp(context);
/// ```
class HomeRoute extends TpRouteData {
  const HomeRoute();

  @override
  String get routeName => 'tp_router_HomeRoute';

  static const String kName = 'tp_router_HomeRoute';

  /// Creates a [HomeRoute] from [TpRouteData].
  static HomeRoute fromData(TpRouteData data) {
    if (data is HomeRoute) return data;
    final settings = data;
    return HomeRoute();
  }

  /// The route info for this route.
  static final TpRouteInfo routeInfo = TpRouteInfo(
    path: '/',
    name: 'tp_router_HomeRoute',
    isInitial: true,
    params: [],
    builder: (settings) {
      return HomePage();
    },
  );

  @override
  String get fullPath {
    var p = '/';
    return p;
  }
}

class MainShellRoute {
  static const navigatorKey = MainNavKey();
  static final _branchKey0 = TpNavigatorKeyRegistry.getOrCreate(
      TpNavKey.value(navigatorKey.key, branch: 0));
  static final _branchKey1 = TpNavigatorKeyRegistry.getOrCreate(
      TpNavKey.value(navigatorKey.key, branch: 1));
  static final _branchKey2 = TpNavigatorKeyRegistry.getOrCreate(
      TpNavKey.value(navigatorKey.key, branch: 2));

  static final TpStatefulShellRouteInfo routeInfo = TpStatefulShellRouteInfo(
    builder: (context, navigationShell) =>
        MainShellPage(navigationShell: navigationShell),
    branches: [
      [
        HomeRoute.routeInfo,
      ],
      [
        SettingsRoute.routeInfo,
      ],
      [
        DashboardShellRoute.routeInfo,
      ],
    ],
    branchNavigatorKeys: [
      _branchKey0,
      _branchKey1,
      _branchKey2,
    ],
    observersBuilder: () => [
      AObserver(),
    ],
  );
}

/// Route class for [SettingsPage].
///
/// Usage:
/// ```dart
/// SettingsRoute().tp(context);
/// ```
class SettingsRoute extends TpRouteData {
  const SettingsRoute();

  @override
  String get routeName => 'tp_router_SettingsRoute';

  static const String kName = 'tp_router_SettingsRoute';

  /// Creates a [SettingsRoute] from [TpRouteData].
  static SettingsRoute fromData(TpRouteData data) {
    if (data is SettingsRoute) return data;
    final settings = data;
    return SettingsRoute();
  }

  /// The route info for this route.
  static final TpRouteInfo routeInfo = TpRouteInfo(
    path: '/settings',
    name: 'tp_router_SettingsRoute',
    isInitial: false,
    params: [],
    builder: (settings) {
      return SettingsPage();
    },
  );

  @override
  String get fullPath {
    var p = '/settings';
    return p;
  }
}

/// Route class for [MemoryDetailPage].
///
/// Usage:
/// ```dart
/// MemoryDetailRoute(memory2: value).tp(context);
/// ```
class MemoryDetailRoute extends TpRouteData {
  final MemoryDetail memory2;
  final MemoryDetail memory;

  const MemoryDetailRoute({
    required this.memory2,
    this.memory =
        const MemoryDetail(id: 'internal', content: 'Internal Default'),
  });

  @override
  String get routeName => 'tp_router_MemoryDetailRoute';

  static const String kName = 'tp_router_MemoryDetailRoute';

  /// Creates a [MemoryDetailRoute] from [TpRouteData].
  static MemoryDetailRoute fromData(TpRouteData data) {
    if (data is MemoryDetailRoute) return data;
    final settings = data;
    final memory2 = (() {
      final extra = settings.extra;
      if (extra.containsKey('memory2')) {
        return extra['memory2'] as MemoryDetail;
      }
      if (extra is MemoryDetail) {
        return extra;
      }
      throw ArgumentError('Missing required parameter: memory2');
    })();
    final memory = (() {
      final extra = settings.extra;
      if (extra.containsKey('memory')) {
        return extra['memory'] as MemoryDetail;
      }
      if (extra is MemoryDetail) {
        return extra;
      }
      return null;
    })();
    return MemoryDetailRoute(
        memory2: memory2,
        memory: (memory ??
            const MemoryDetail(id: 'internal', content: 'Internal Default')));
  }

  /// The route info for this route.
  static final TpRouteInfo routeInfo = TpRouteInfo(
    path: '/memory-detail',
    name: 'tp_router_MemoryDetailRoute',
    isInitial: false,
    params: [
      TpParamInfo(
        name: 'memory2',
        urlName: 'memory2',
        type: 'MemoryDetail',
        isRequired: true,
        source: 'extra',
      ),
      TpParamInfo(
        name: 'memory',
        urlName: 'memory',
        type: 'MemoryDetail',
        isRequired: false,
        source: 'extra',
      ),
    ],
    builder: (settings) {
      final memory2 = (() {
        final extra = settings.extra;
        if (extra.containsKey('memory2')) {
          return extra['memory2'] as MemoryDetail;
        }
        if (extra is MemoryDetail) {
          return extra;
        }
        throw ArgumentError('Missing required parameter: memory2');
      })();
      final memory = (() {
        final extra = settings.extra;
        if (extra.containsKey('memory')) {
          return extra['memory'] as MemoryDetail;
        }
        if (extra is MemoryDetail) {
          return extra;
        }
        return null;
      })();
      return MemoryDetailPage(
          memory2: memory2,
          memory: (memory ??
              const MemoryDetail(id: 'internal', content: 'Internal Default')));
    },
  );

  @override
  String get fullPath {
    var p = '/memory-detail';
    return p;
  }

  @override
  Map<String, dynamic> get extra => {
        'memory2': memory2,
        'memory': memory,
      };
}

/// Route class for [ProtectedPage].
///
/// Usage:
/// ```dart
/// ProtectedRoute().tp(context);
/// ```
class ProtectedRoute extends TpRouteData {
  const ProtectedRoute();

  @override
  String get routeName => 'tp_router_ProtectedRoute';

  static const String kName = 'tp_router_ProtectedRoute';

  /// Creates a [ProtectedRoute] from [TpRouteData].
  static ProtectedRoute fromData(TpRouteData data) {
    if (data is ProtectedRoute) return data;
    final settings = data;
    return ProtectedRoute();
  }

  /// The route info for this route.
  static final TpRouteInfo routeInfo = TpRouteInfo(
    path: '/protected',
    name: 'tp_router_ProtectedRoute',
    isInitial: false,
    params: [],
    redirect: (context, data) async {
      final route = ProtectedRoute.fromData(data);
      return AuthRedirect().handle(context, route);
    },
    builder: (settings) {
      return ProtectedPage();
    },
  );

  @override
  String get fullPath {
    var p = '/protected';
    return p;
  }
}

/// Route class for [RouteRemovalDemoPage].
///
/// Usage:
/// ```dart
/// RouteRemovalDemoRoute().tp(context);
/// ```
class RouteRemovalDemoRoute extends TpRouteData {
  const RouteRemovalDemoRoute();

  @override
  String get routeName => 'tp_router_RouteRemovalDemoRoute';

  static const String kName = 'tp_router_RouteRemovalDemoRoute';

  /// Creates a [RouteRemovalDemoRoute] from [TpRouteData].
  static RouteRemovalDemoRoute fromData(TpRouteData data) {
    if (data is RouteRemovalDemoRoute) return data;
    final settings = data;
    return RouteRemovalDemoRoute();
  }

  /// The route info for this route.
  static final TpRouteInfo routeInfo = TpRouteInfo(
    path: '/route-removal-demo',
    name: 'tp_router_RouteRemovalDemoRoute',
    isInitial: false,
    params: [],
    builder: (settings) {
      return RouteRemovalDemoPage();
    },
  );

  @override
  String get fullPath {
    var p = '/route-removal-demo';
    return p;
  }
}

/// Route class for [RouteStackPageA].
///
/// Usage:
/// ```dart
/// RouteStackPageARoute().tp(context);
/// ```
class RouteStackPageARoute extends TpRouteData {
  const RouteStackPageARoute();

  @override
  String get routeName => 'tp_router_RouteStackPageARoute';

  static const String kName = 'tp_router_RouteStackPageARoute';

  /// Creates a [RouteStackPageARoute] from [TpRouteData].
  static RouteStackPageARoute fromData(TpRouteData data) {
    if (data is RouteStackPageARoute) return data;
    final settings = data;
    return RouteStackPageARoute();
  }

  /// The route info for this route.
  static final TpRouteInfo routeInfo = TpRouteInfo(
    path: '/route-stack/a',
    name: 'tp_router_RouteStackPageARoute',
    isInitial: false,
    params: [],
    builder: (settings) {
      return RouteStackPageA();
    },
  );

  @override
  String get fullPath {
    var p = '/route-stack/a';
    return p;
  }
}

/// Route class for [RouteStackPageB].
///
/// Usage:
/// ```dart
/// RouteStackPageBRoute().tp(context);
/// ```
class RouteStackPageBRoute extends TpRouteData {
  const RouteStackPageBRoute();

  @override
  String get routeName => 'tp_router_RouteStackPageBRoute';

  static const String kName = 'tp_router_RouteStackPageBRoute';

  /// Creates a [RouteStackPageBRoute] from [TpRouteData].
  static RouteStackPageBRoute fromData(TpRouteData data) {
    if (data is RouteStackPageBRoute) return data;
    final settings = data;
    return RouteStackPageBRoute();
  }

  /// The route info for this route.
  static final TpRouteInfo routeInfo = TpRouteInfo(
    path: '/route-stack/b',
    name: 'tp_router_RouteStackPageBRoute',
    isInitial: false,
    params: [],
    builder: (settings) {
      return RouteStackPageB();
    },
  );

  @override
  String get fullPath {
    var p = '/route-stack/b';
    return p;
  }
}

/// Route class for [RouteStackPageC].
///
/// Usage:
/// ```dart
/// RouteStackPageCRoute().tp(context);
/// ```
class RouteStackPageCRoute extends TpRouteData {
  const RouteStackPageCRoute();

  @override
  String get routeName => 'tp_router_RouteStackPageCRoute';

  static const String kName = 'tp_router_RouteStackPageCRoute';

  /// Creates a [RouteStackPageCRoute] from [TpRouteData].
  static RouteStackPageCRoute fromData(TpRouteData data) {
    if (data is RouteStackPageCRoute) return data;
    final settings = data;
    return RouteStackPageCRoute();
  }

  /// The route info for this route.
  static final TpRouteInfo routeInfo = TpRouteInfo(
    path: '/route-stack/c',
    name: 'tp_router_RouteStackPageCRoute',
    isInitial: false,
    params: [],
    builder: (settings) {
      return RouteStackPageC();
    },
  );

  @override
  String get fullPath {
    var p = '/route-stack/c';
    return p;
  }
}

/// Route class for [UserPage].
///
/// Usage:
/// ```dart
/// UserRoute(id: 123).tp(context);
/// ```
class UserRoute extends TpRouteData {
  final int id;
  final String name;
  final int age;

  const UserRoute({
    required this.id,
    this.name = '',
    this.age = 0,
  });

  @override
  String get routeName => 'tp_router_UserRoute';

  static const String kName = 'tp_router_UserRoute';

  /// Creates a [UserRoute] from [TpRouteData].
  static UserRoute fromData(TpRouteData data) {
    if (data is UserRoute) return data;
    final settings = data;
    final id = (() {
      final raw = settings.pathParams['id'];
      if (raw == null) {
        throw ArgumentError('Missing required parameter: id');
      }
      final parsed = int.tryParse(raw);
      if (parsed == null) {
        throw ArgumentError('Invalid int value for: id');
      }
      return parsed;
    })();
    final name = settings.queryParams['name'];
    final age = (() {
      final raw = settings.queryParams['age'];
      if (raw == null) {
        return null;
      }
      final parsed = int.tryParse(raw);
      if (parsed == null) {
        return null;
      }
      return parsed;
    })();
    return UserRoute(id: id, name: (name ?? ''), age: (age ?? 0));
  }

  /// The route info for this route.
  static final TpRouteInfo routeInfo = TpRouteInfo(
    path: '/user/:id',
    name: 'tp_router_UserRoute',
    isInitial: false,
    params: [
      TpParamInfo(
        name: 'id',
        urlName: 'id',
        type: 'int',
        isRequired: true,
        source: 'path',
      ),
      TpParamInfo(
        name: 'name',
        urlName: 'name',
        type: 'String',
        isRequired: false,
        source: 'query',
      ),
      TpParamInfo(
        name: 'age',
        urlName: 'age',
        type: 'int',
        isRequired: false,
        source: 'query',
      ),
    ],
    builder: (settings) {
      final id = (() {
        final raw = settings.pathParams['id'];
        if (raw == null) {
          throw ArgumentError('Missing required parameter: id');
        }
        final parsed = int.tryParse(raw);
        if (parsed == null) {
          throw ArgumentError('Invalid int value for: id');
        }
        return parsed;
      })();
      final name = settings.queryParams['name'];
      final age = (() {
        final raw = settings.queryParams['age'];
        if (raw == null) {
          return null;
        }
        final parsed = int.tryParse(raw);
        if (parsed == null) {
          return null;
        }
        return parsed;
      })();
      return UserPage(id: id, name: (name ?? ''), age: (age ?? 0));
    },
  );

  @override
  String get fullPath {
    var p = '/user/:id';
    p = p.replaceAll(':id', id.toString());
    final queryParts = <String>[];
    queryParts.add('name=${Uri.encodeComponent(name.toString())}');
    queryParts.add('age=${Uri.encodeComponent(age.toString())}');
    if (queryParts.isNotEmpty) p = '$p?${queryParts.join('&')}';
    return p;
  }
}

/// All generated routes in the application.
///
/// Use this list to initialize [TpRouter]:
/// ```dart
/// final router = TpRouter(routes: tpRoutes);
/// ```
List<TpRouteBase> get tpRoutes => [
      DetailsRoute.routeInfo,
      LoginRoute.routeInfo,
      MainShellRoute.routeInfo,
      MemoryDetailRoute.routeInfo,
      ProtectedRoute.routeInfo,
      RouteRemovalDemoRoute.routeInfo,
      RouteStackPageARoute.routeInfo,
      RouteStackPageBRoute.routeInfo,
      RouteStackPageCRoute.routeInfo,
      UserRoute.routeInfo,
    ];
